name: Daily AI News Robot

on:
  schedule:
    - cron: '0 0 * * *' # 每天北京时间早上 8 点
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检查代码
        uses: actions/checkout@v3

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 强制安装所需工具包
        # 这里直接在云端安装剥离网页用的 cheerio，以及原来那两个
        run: npm install axios rss-parser cheerio

      - name: 运行超级机器人
        env:
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: node index.js
